version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 5000:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    ports:
      - 5001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: